ALL_TIMES = [
    ("00:00", "00:00"),
    ("00:30", "00:30"),
    ("01:00", "01:00"),
    ("01:30", "01:30"),
    ("02:00", "02:00"),
    ("02:30", "02:30"),
    ("03:00", "03:00"),
    ("03:30", "03:30"),
    ("04:00", "04:00"),
    ("04:30", "04:30"),
    ("05:00", "05:00"),
    ("05:30", "05:30"),
    ("06:00", "06:00"),
    ("06:30", "06:30"),
    ("07:00", "07:00"),
    ("07:30", "07:30"),
    ("08:00", "08:00"),
    ("08:30", "08:30"),
    ("09:00", "09:00"),
    ("09:30", "09:30"),
    ("10:00", "10:00"),
    ("10:30", "10:30"),
    ("11:00", "11:00"),
    ("11:30", "11:30"),
    ("12:00", "12:00"),
    ("12:30", "12:30"),
    ("13:00", "13:00"),
    ("13:30", "13:30"),
    ("14:00", "14:00"),
    ("14:30", "14:30"),
    ("15:00", "15:00"),
    ("15:30", "15:30"),
    ("16:00", "16:00"),
    ("16:30", "16:30"),
    ("17:00", "17:00"),
    ("17:30", "17:30"),
    ("18:00", "18:00"),
    ("18:30", "18:30"),
    ("19:00", "19:00"),
    ("19:30", "19:30"),
    ("20:00", "20:00"),
    ("20:30", "20:30"),
    ("21:00", "21:00"),
    ("21:30", "21:30"),
    ("22:00", "22:00"),
    ("22:30", "22:30"),
    ("23:00", "23:00"),
    ("23:30", "23:30"),
]

LANGUAGES = [
    ("af", "Afrikaans"),
    ("sq", "Albanian"),
    ("am", "Amharic"),
    ("ar", "Arabic"),
    ("hy", "Armenian"),
    ("az", "Azerbaijani"),
    ("eu", "Basque"),
    ("be", "Belarusian"),
    ("bn", "Bengali"),
    ("bs", "Bosnian"),
    ("bg", "Bulgarian"),
    ("ca", "Catalan"),
    ("ceb", "Cebuano"),
    ("zh", "Chinese (Simplified)"),
    ("zh-TW", "Chinese (Traditional)"),
    ("co", "Corsican"),
    ("hr", "Croatian"),
    ("cs", "Czech"),
    ("da", "Danish"),
    ("nl", "Dutch"),
    ("en", "English"),
    ("eo", "Esperanto"),
    ("et", "Estonian"),
    ("fi", "Finnish"),
    ("fr", "French"),
    ("fy", "Frisian"),
    ("gl", "Galician"),
    ("ka", "Georgian"),
    ("de", "German"),
    ("el", "Greek"),
    ("gu", "Gujarati"),
    ("ht", "Haitian Creole"),
    ("ha", "Hausa"),
    ("haw", "Hawaiian"),
    ("he", "Hebrew"),
    ("hi", "Hindi"),
    ("hmn", "Hmong"),
    ("hu", "Hungarian"),
    ("is", "Icelandic"),
    ("ig", "Igbo"),
    ("id", "Indonesian"),
    ("ga", "Irish"),
    ("it", "Italian"),
    ("ja", "Japanese"),
    ("jw", "Javanese"),
    ("kn", "Kannada"),
    ("kk", "Kazakh"),
    ("km", "Khmer"),
    ("rw", "Kinyarwanda"),
    ("ko", "Korean"),
    ("ku", "Kurdish (Kurmanji)"),
    ("ky", "Kyrgyz"),
    ("lo", "Lao"),
    ("la", "Latin"),
    ("lv", "Latvian"),
    ("lt", "Lithuanian"),
    ("lb", "Luxembourgish"),
    ("mk", "Macedonian"),
    ("mg", "Malagasy"),
    ("ms", "Malay"),
    ("ml", "Malayalam"),
    ("mt", "Maltese"),
    ("mi", "Maori"),
    ("mr", "Marathi"),
    ("mn", "Mongolian"),
    ("my", "Myanmar (Burmese)"),
    ("ne", "Nepali"),
    ("no", "Norwegian"),
    ("ny", "Nyanja (Chichewa)"),
    ("or", "Odia (Oriya)"),
    ("ps", "Pashto"),
    ("fa", "Persian"),
    ("pl", "Polish"),
    ("pt", "Portuguese"),
    ("pa", "Punjabi"),
    ("ro", "Romanian"),
    ("ru", "Russian"),
    ("sm", "Samoan"),
    ("gd", "Scots Gaelic"),
    ("sr", "Serbian"),
    ("st", "Sesotho"),
    ("sn", "Shona"),
    ("sd", "Sindhi"),
    ("si", "Sinhala (Sinhalese)"),
    ("sk", "Slovak"),
    ("sl", "Slovenian"),
    ("so", "Somali"),
    ("es", "Spanish"),
    ("su", "Sundanese"),
    ("sw", "Swahili"),
    ("sv", "Swedish"),
    ("tl", "Tagalog (Filipino)"),
    ("tg", "Tajik"),
    ("ta", "Tamil"),
    ("tt", "Tatar"),
    ("te", "Telugu"),
    ("th", "Thai"),
    ("tr", "Turkish"),
    ("tk", "Turkmen"),
    ("uk", "Ukrainian"),
    ("ur", "Urdu"),
    ("ug", "Uyghur"),
    ("uz", "Uzbek"),
    ("vi", "Vietnamese"),
    ("cy", "Welsh"),
    ("xh", "Xhosa"),
    ("yi", "Yiddish"),
    ("yo", "Yoruba"),
    ("zu", "Zulu"),
]
CITIZENSHIP = [
    ("afghanistan", "Afghanistan"),
    ("albania", "Albania"),
    ("algeria", "Algeria"),
    ("american_samoa", "American Samoa"),
    ("andorra", "Andorra"),
    ("angola", "Angola"),
    ("anguilla", "Anguilla"),
    ("antigua_and_barbuda", "Antigua and Barbuda"),
    ("argentina", "Argentina"),
    ("armenia", "Armenia"),
    ("aruba", "Aruba"),
    ("australia", "Australia"),
    ("austria", "Austria"),
    ("azerbaijan", "Azerbaijan"),
    ("bahamas", "Bahamas"),
    ("bahrain", "Bahrain"),
    ("bangladesh", "Bangladesh"),
    ("barbados", "Barbados"),
    ("belarus", "Belarus"),
    ("belgium", "Belgium"),
    ("belize", "Belize"),
    ("benin", "Benin"),
    ("bermuda", "Bermuda"),
    ("bhutan", "Bhutan"),
    ("bolivia", "Bolivia"),
    ("bosnia_and_herzegovina", "Bosnia and Herzegovina"),
    ("botswana", "Botswana"),
    ("brazil", "Brazil"),
    ("brunei", "Brunei"),
    ("bulgaria", "Bulgaria"),
    ("burkina_faso", "Burkina Faso"),
    ("burundi", "Burundi"),
    ("cambodia", "Cambodia"),
    ("cameroon", "Cameroon"),
    ("canada", "Canada"),
    ("cape_verde", "Cape Verde"),
    ("cayman_islands", "Cayman Islands"),
    ("central_african_republic", "Central African Republic"),
    ("chad", "Chad"),
    ("chile", "Chile"),
    ("china", "China"),
    ("colombia", "Colombia"),
    ("comoros", "Comoros"),
    ("congo", "Congo"),
    ("cook_islands", "Cook Islands"),
    ("costa_rica", "Costa Rica"),
    ("croatia", "Croatia"),
    ("cuba", "Cuba"),
    ("cyprus", "Cyprus"),
    ("czech_republic", "Czech Republic"),
    ("denmark", "Denmark"),
    ("djibouti", "Djibouti"),
    ("dominica", "Dominica"),
    ("dominican_republic", "Dominican Republic"),
    ("east_timor", "East Timor"),
    ("ecuador", "Ecuador"),
    ("egypt", "Egypt"),
    ("el_salvador", "El Salvador"),
    ("equatorial_guinea", "Equatorial Guinea"),
    ("eritrea", "Eritrea"),
    ("estonia", "Estonia"),
    ("eswatini", "Eswatini"),
    ("ethiopia", "Ethiopia"),
    ("fiji", "Fiji"),
    ("finland", "Finland"),
    ("france", "France"),
    ("gabon", "Gabon"),
    ("gambia", "Gambia"),
    ("georgia", "Georgia"),
    ("germany", "Germany"),
    ("ghana", "Ghana"),
    ("greece", "Greece"),
    ("greenland", "Greenland"),
    ("grenada", "Grenada"),
    ("guatemala", "Guatemala"),
    ("guinea", "Guinea"),
    ("guinea_bissau", "Guinea-Bissau"),
    ("guyana", "Guyana"),
    ("haiti", "Haiti"),
    ("honduras", "Honduras"),
    ("hungary", "Hungary"),
    ("iceland", "Iceland"),
    ("india", "India"),
    ("indonesia", "Indonesia"),
    ("iran", "Iran"),
    ("iraq", "Iraq"),
    ("ireland", "Ireland"),
    ("israel", "Israel"),
    ("italy", "Italy"),
    ("jamaica", "Jamaica"),
    ("japan", "Japan"),
    ("jordan", "Jordan"),
    ("kazakhstan", "Kazakhstan"),
    ("kenya", "Kenya"),
    ("kiribati", "Kiribati"),
    ("north_korea", "North Korea"),
    ("south_korea", "South Korea"),
    ("kosovo", "Kosovo"),
    ("kuwait", "Kuwait"),
    ("kyrgyzstan", "Kyrgyzstan"),
    ("laos", "Laos"),
    ("latvia", "Latvia"),
    ("lebanon", "Lebanon"),
    ("lesotho", "Lesotho"),
    ("liberia", "Liberia"),
    ("libya", "Libya"),
    ("liechtenstein", "Liechtenstein"),
    ("lithuania", "Lithuania"),
    ("luxembourg", "Luxembourg"),
    ("madagascar", "Madagascar"),
    ("malawi", "Malawi"),
    ("malaysia", "Malaysia"),
    ("maldives", "Maldives"),
    ("mali", "Mali"),
    ("malta", "Malta"),
    ("marshall_islands", "Marshall Islands"),
    ("mauritania", "Mauritania"),
    ("mauritius", "Mauritius"),
    ("mexico", "Mexico"),
    ("micronesia", "Micronesia"),
    ("moldova", "Moldova"),
    ("monaco", "Monaco"),
    ("mongolia", "Mongolia"),
    ("montenegro", "Montenegro"),
    ("morocco", "Morocco"),
    ("mozambique", "Mozambique"),
    ("myanmar", "Myanmar"),
    ("namibia", "Namibia"),
    ("nauru", "Nauru"),
    ("nepal", "Nepal"),
    ("netherlands", "Netherlands"),
    ("new_zealand", "New Zealand"),
    ("nicaragua", "Nicaragua"),
    ("niger", "Niger"),
    ("nigeria", "Nigeria"),
    ("north_macedonia", "North Macedonia"),
    ("norway", "Norway"),
    ("oman", "Oman"),
    ("pakistan", "Pakistan"),
    ("palau", "Palau"),
    ("panama", "Panama"),
    ("papua_new_guinea", "Papua New Guinea"),
    ("paraguay", "Paraguay"),
    ("peru", "Peru"),
    ("philippines", "Philippines"),
    ("poland", "Poland"),
    ("portugal", "Portugal"),
    ("qatar", "Qatar"),
    ("romania", "Romania"),
    ("russian_federation", "Russian Federation"),
    ("rwanda", "Rwanda"),
    ("saint_kitts_and_nevis", "Saint Kitts and Nevis"),
    ("saint_lucia", "Saint Lucia"),
    ("saint_vincent_and_the_grenadines", "Saint Vincent and the Grenadines"),
    ("samoa", "Samoa"),
    ("san_marino", "San Marino"),
    ("sao_tome_and_principe", "Sao Tome and Principe"),
    ("saudi_arabia", "Saudi Arabia"),
    ("senegal", "Senegal"),
    ("serbia", "Serbia"),
    ("seychelles", "Seychelles"),
    ("sierra_leone", "Sierra Leone"),
    ("singapore", "Singapore"),
    ("slovakia", "Slovakia"),
    ("slovenia", "Slovenia"),
    ("solomon_islands", "Solomon Islands"),
    ("somalia", "Somalia"),
    ("south_africa", "South Africa"),
    ("south_sudan", "South Sudan"),
    ("spain", "Spain"),
    ("sri_lanka", "Sri Lanka"),
    ("sudan", "Sudan"),
    ("suriname", "Suriname"),
    ("sweden", "Sweden"),
    ("switzerland", "Switzerland"),
    ("syria", "Syria"),
    ("taiwan", "Taiwan"),
    ("tajikistan", "Tajikistan"),
    ("tanzania", "Tanzania"),
    ("thailand", "Thailand"),
    ("togo", "Togo"),
    ("tonga", "Tonga"),
    ("trinidad_and_tobago", "Trinidad and Tobago"),
    ("tunisia", "Tunisia"),
    ("turkey", "Turkey"),
    ("turkmenistan", "Turkmenistan"),
    ("tuvalu", "Tuvalu"),
    ("uganda", "Uganda"),
    ("ukraine", "Ukraine"),
    ("united_arab_emirates", "United Arab Emirates"),
    ("united_kingdom", "United Kingdom"),
    ("united_states", "United States"),
    ("uruguay", "Uruguay"),
    ("uzbekistan", "Uzbekistan"),
    ("vanuatu", "Vanuatu"),
    ("vatican_city", "Vatican City"),
    ("venezuela", "Venezuela"),
    ("vietnam", "Vietnam"),
    ("yemen", "Yemen"),
    ("zambia", "Zambia"),
    ("zimbabwe", "Zimbabwe"),
]
